GET http://localhost:3000

### GET all pets
GET http://localhost:3000/v1/api/pets

### DELETE a pet
DELETE http://localhost:3000/v1/api/pets/2

### POST create a pet
## `pet_id`, `name`, `dob`, `client_email`, `isArchived`
POST http://localhost:3000/v1/api/pets
Content-Type: application/json

{
  "name1": "Buddy",
  "dob": "2019-01-01",
  "clientEmail": "buddy@buddy.com"
}

### GET all meds
GET http://localhost:3000/v1/api/meds

### GET logs for pet 
GET http://localhost:3000/v1/api/logs/petId/2


### GET prescriptions for pet 

GET http://localhost:3000/v1/api/prescriptions/petId/2
